---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: zoho
  namespace: hajimari
spec:
  name: ZoHo Mail
  group: Communication
  icon: mdi:mail
  url: https://mail.zoho.com/
  info: ZoHo E-Mail
  location: 100
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: reddit
  namespace: hajimari
spec:
  name: Reddit
  group: Communication
  icon: simple-icons:reddit
  url: https://old.reddit.com/
  info: Social Media
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: linkedin
  namespace: hajimari
spec:
  name: LinkedIn
  group: Business
  icon: simple-icons:linkedin
  url: https://linkedin.com/
  info: Business Networking
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: netflix
  namespace: hajimari
spec:
  name: Netflix
  group: Entertainment
  icon: simple-icons:netflix
  url: https://netflix.com/
  info: Streaming
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: amazon-video
  namespace: hajimari
spec:
  name: Amazon Video
  group: Entertainment
  icon: simple-icons:amazon
  url: https://www.amazon.com/gp/video/storefront/
  info: Streaming
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: youtube
  namespace: hajimari
spec:
  name: Youtube
  group: Entertainment
  icon: simple-icons:youtube
  url: https://youtube.com/feed/subscriptions
  info: Streaming
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: spotify
  namespace: hajimari
spec:
  name: Spotify
  group: Entertainment
  icon: simple-icons:spotify
  url: https://browse.spotify.com/
  info: Music Streaming
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: makerworld
  namespace: hajimari
spec:
  name: Makerworld
  group: 3D Printing
  icon: mdi:printer-3d
  url: https://makerworld.com/
  info: 3D Printing Community
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: printables
  namespace: hajimari
spec:
  name: Printables
  group: 3D Printing
  icon: simple-icons:printables
  url: https://printables.com/
  info: 3D Printing Community
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Bookmark
metadata:
  name: thingiverse
  namespace: hajimari
spec:
  name: Thingiverse
  group: 3D Printing
  icon: simple-icons:thingiverse
  url: https://thingiverse.com/
  info: 3D Printing Community