---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
  data:
    - secretKey: CLIENTKEY
      remoteRef:
        key: ADSBHUB_CLIENTKEY
    - secretKey: FEEDER_ID
      remoteRef:
        key: FLIGHAWARE_FEEDER_ID
    - secretKey: FR24KEY
      remoteRef:
        key: FR24KEY
    - secretKey: OPENSKY_USERNAME
      remoteRef:
        key: OPENSKY_USERNAME
    - secretKey: OPENSKY_SERIAL
      remoteRef:
        key: OPENSKY_SERIAL
    - secretKey: UUID
      remoteRef:
        key: ULTRAFEEDER_UUID
    - secretKey: TAR1090_PAGETITLE
      remoteRef:
        key: TAR1090_PAGETITLE
    - secretKey: MLAT_USER
      remoteRef:
        key: MLAT_USER
    - secretKey: HEYWHATSTHAT_ALTS
      remoteRef:
        key: HEYWHATSTHAT_ALTS
    - secretKey: HEYWHATSTHAT_PANORAMA_ID
      remoteRef:
        key: HEYWHATSTHAT_PANORAMA_ID
    - secretKey: API_KEY
      remoteRef:
        key: PLANEWATCH_API_KEY
    - secretKey: LAT
      remoteRef:
        key: LAT
    - secretKey: READSB_LAT
      remoteRef:
        key: LAT
    - secretKey: LONG
      remoteRef:
        key: LONG
    - secretKey: READSB_LON
      remoteRef:
        key: LONG
    - secretKey: ALT
      remoteRef:
        key: ALT
    - secretKey: READSB_ALT
      remoteRef:
        key: ALT
