---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-planewatch
spec:
  type: ClusterIP
  ports:
    - name: mlat-beast-output
      port: 31005
      targetPort: 31005
      protocol: TCP
  selector:
    app.kubernetes.io/controller: planewatch
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
