---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: {{ .Release.Name }}
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        SONARR__AUTH__APIKEY: "{{ `{{ .SONARR_API_KEY }}` }}"
  dataFrom:
    - rewrite:
        - source:
            key: SONARR_API_KEY
          target:
            key: SONARR_API_KEY
