---
apiVersion: v2
description: A Helm chart to install the recyclarr cronjob.
name: recyclarr
version: 0.1.3
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
