kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: litellm-db
  namespace: litellm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
{{- if and .Values.cluster.storage .Values.cluster.storage.config .Values.cluster.storage.config.storageClassName }}
  storageClassName: {{ .Values.cluster.storage.config.storageClassName }}
{{- end }}
