apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-nmstate-
  name: openshift-nmstate-cluster
  namespace: openshift-nmstate
spec:
  targetNamespaces:
    - openshift-nmstate
  upgradeStrategy: Default