---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-data-volume
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.media.nfs.server }}
    path: {{ .Values.media.nfs.path }}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-data-volume
  labels:
    kasten/backup: "false"
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Mi
  volumeName: lidarr-data-volume
  storageClassName: ""