{{ $at := index .Values "app-template" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $at.persistence.data.existingClaim }}
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.storage.media.nfs.server }}
    path: {{ .Values.storage.media.nfs.path }}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $at.persistence.data.existingClaim }}
  labels:
    kasten/skip: "true"
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Mi
  volumeName: {{ $at.persistence.data.existingClaim }}
  storageClassName: ""