---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager-operator
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.cluster.admin_email }}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
      dns01:
        route53:
          region: {{ .Values.aws.region }}
          hostedZoneID: {{ .Values.aws.hosted_zone_id }}
          accessKeyID: {{ .Values.aws.access_key_id }}
          secretAccessKeySecretRef:
            name: certificates-secret
            key: secretAccessKey
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager-operator
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.cluster.admin_email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
      dns01:
        route53:
          region: {{ .Values.aws.region }}
          hostedZoneID: {{ .Values.aws.hosted_zone_id }}
          accessKeyID: {{ .Values.aws.access_key_id }}
          secretAccessKeySecretRef:
            name: certificates-secret
            key: secretAccessKey