---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $(SECRET_ADMIN_EMAIL)
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector:
        dnsZones:
          - $(SECRET_TLD)
      dns01:
        route53:
          region: $(AWS_REGION)
          hostedZoneID: $(AWS_HOSTED_ZONE_ID)
          accessKeyID: $(AWS_ACCESS_KEY_ID)
          secretAccessKeySecretRef:
            name: route53-access-key
            key: secretAccessKey
