apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: changedetection
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: changedetection
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/media-application
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}
          
        - name: storage.storageClassName
          value: {{ .Values.config.storageClassName }}
        - name: storage.media.nfs.server
          value: {{ .Values.media.nfs.server }}
        - name: storage.media.nfs.path
          value: {{ .Values.media.nfs.path }}

        - name: application.name
          value: changedetection
        - name: application.group
          value: Utilities
        - name: application.icon
          value: magnify
        - name: application.image
          value: 'https://www.bazarr.media/assets/img/logo.png'
        - name: application.description
          value: "Web Site Change Detection"
        - name: app-template.service.main.ports.http.port
          value: '5000'

        # renovate custom-docker versioning=loose
        - name: app-template.controllers.main.containers.main.image.repository
          value: ghcr.io/dgtlmoon/changedetection.io
        - name: app-template.controllers.main.containers.main.image.tag
          value: 0.49.4
        - name: app-template.controllers.main.containers.main.image.pullPolicy
          value: IfNotPresent
        - name: app-template.controllers.main.containers.main.env.TZ
          value: America/New_York

        - name: app-template.serviceAccount.name
          value: cyberchchangedetectionef-sa
        - name: app-template.persistence.data.existingClaim
          value: changedetection-data-volume
        - name: app-template.persistence.config.existingClaim
          value: changedetection-config
        - name: app-template.persistence.config.globalMounts[0].path
          value: /datastore

        - name: app-template.defaultPodOptions.labels.app
          value: changedetection
        - name: app-template.defaultPodOptions.labels.version
          value: 0.45.22

        # - name: app-template.controllers.main.containers.main.env.WEBDRIVER_URL
        #   value: wss://browserless/?stealth=true

        - name: app-template.controllers.main.containers.main.env.PLAYWRIGHT_DRIVER_URL
          value: ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
