apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard-cert-tls
  namespace: openshift-ingress
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "openshift-ingress"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
  secretName: apps-wildcard-cert-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: apps.openshift.$(SECRET_TLD)
  dnsNames: 
    - "apps.openshift.$(SECRET_TLD)"
    - "*.apps.openshift.$(SECRET_TLD)"
