---
apiVersion: v2
description: A Helm chart to install Plex.
name: media-plex
version: 0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
dependencies:
  - name: app-template
    version: "3.1.0"
    repository: "@bjw-s"
