app-template:
  controllers:
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            # renovate: docker-image versioning=loose
            repository: ghcr.io/onedr0p/plex
            tag: 1.40.0.7998-c29d4c0c8
            pullPolicy: IfNotPresent
          env:
            TZ: TIMEZONE

  serviceAccount:
    name: plex-sa

  service:
    main:
      # type: LoadBalancer
      # loadBalancerIP: "192.168.64.41"
      controller: main
      ports:
        http:
          port: 32400
        dlna-udp:
          port: 1900
          protocol: UDP
        dlna-tcp:
          port: 32469
          protocol: TCP
        plex-companion:
          port: 3005
          protocol: TCP
        plex-roku:
          port: 8234
          protocol: TCP
        gdm-1:
          port: 32410
          protocol: UDP
        gdm-2:
          port: 32412
          protocol: UDP
        gdm3:
          port: 32413
          protocol: UDP
        gdm-4:
          port: 32414
          protocol: UDP
        bonjour:
          port: 5353
          protocol: UDP

  ingress:
    main:
      enabled: true
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/stakater/ForecastleIcons/master/alert-manager.png"
        forecastle.stakater.com/group: "Media"
        # kubernetes.io/ingress.class: nginx
        # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/configuration-snippet: |
        #   location = / {
        #     if ($http_x_plex_device = ""){
        #       return 301 $scheme://$host/web/index.html;
        #     }
        #   }
        route.openshift.io/termination: "edge"
      hosts:
        - host: &host "your_host"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http

  persistence:
    config:
      enabled: true
      existingClaim: plex-config

    data:
      enabled: true
      existingClaim: data-volume
      globalMounts:
        - path: /data

    transcode:
      enabled: true
      type: emptyDir

  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
