apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/k10-kasten-operator-rhmp.kasten-io: ''
  name: k10-kasten-operator-rhmp
  namespace: kasten-io
spec:
  channel: stable
  installPlanApproval: Manual
  name: k10-kasten-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
  startingCSV: k10-kasten-operator-rhmp.v6.5.11
