spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: YOUR_REPO_URL
    targetRevision: HEAD

roles:
  ai:
    enabled: true
  utilities:
    enabled: true

config:
  cluster:
    top_level_domain: example.com
    name: cluster
    admin_email: YOUR_EMAIL
    timezone: YOUR_TIMEZONE
    storage:
      config:
        storageClassName: synology-iscsi
