spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: YOUR_REPO_URL
    targetRevision: HEAD

config:
  cluster:
    top_level_domain: example.com
    name: cluster
    admin_email: YOUR_EMAIL
    timezone: YOUR_TIMEZONE
    storage:
      config:
        storageClassName: synology-iscsi
      media:
        nfs:
          server: nas
          path: /volume1/media

  plex:
    network:
      ip: 192.168.1.10
