apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nmstate-config
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/nmstate-config
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: network.node0.name
          value: {{ .Values.network.node0.name }}
        - name: network.node0.storageIp.ip
          value: {{ .Values.network.node0.storageIp.ip }}
        - name: network.node0.storageIp.prefixLength
          value: "{{ .Values.network.node0.storageIp.prefixLength }}"
        - name: network.node0.storageInterface.name
          value: {{ .Values.network.node0.storageInterface.name }}
        - name: network.node1.name
          value: {{ .Values.network.node1.name }}
        - name: network.node1.storageIp.ip
          value: {{ .Values.network.node1.storageIp.ip }}
        - name: network.node1.storageIp.prefixLength
          value: "{{ .Values.network.node1.storageIp.prefixLength }}"
        - name: network.node1.storageInterface.name
          value: {{ .Values.network.node1.storageInterface.name }}
        - name: network.node2.name
          value: {{ .Values.network.node2.name }}
        - name: network.node2.storageIp.ip
          value: {{ .Values.network.node2.storageIp.ip }}
        - name: network.node2.storageIp.prefixLength
          value: "{{ .Values.network.node2.storageIp.prefixLength }}"
        - name: network.node2.storageInterface.name
          value: {{ .Values.network.node2.storageInterface.name }}
  syncPolicy:
    automated:
      selfHeal: true