---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: {{ .Release.Name }}
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PLEX_TOKEN: "{{ `{{ .PLEX_TOKEN }}` }}"
        FANARTTV_API_KEY: "{{ `{{ .FANARTTV_API_KEY }}` }}"
        TVDB_API_KEY: "{{ `{{ .TVDB_API_KEY }}` }}"
        TMDB_READ_API_TOKEN: "{{ `{{ .TMDB_READ_API_TOKEN }}` }}"
  dataFrom:
    - rewrite:
        - source:
            key: PLEX_TOKEN
          target:
            key: PLEX_TOKEN
        - source:
            key: FANARTTV_API_KEY
          target:
            key: FANARTTV_API_KEY
        - source:
            key: TVDB_API_KEY
          target:
            key: TVDB_API_KEY
        - source:
            key: TMDB_READ_API_TOKEN
          target:
            key: TMDB_READ_API_TOKEN
