---
apiVersion: v2
description: A Helm chart to install the democratic-csi snapshot controller.
name: storage-democratic-csi-snapshot-controller
version: 0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
dependencies:
- name: snapshot-controller
  version: "0.2.4"
  repository: "https://democratic-csi.github.io/charts"
