apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: cert-manager-operator-
  name: cert-manager-operator-cluster
  namespace: cert-manager-operator
spec:
  upgradeStrategy: Default
