---
apiVersion: v2
description: A Helm chart to install forecastle.
name: home-forecastle
version: 0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
dependencies:
- name: forecastle
  version: "v1.0.127"
  repository: "https://stakater.github.io/stakater-charts"