{{- if eq (index .Values "custom-error-pages" "template") "hacker-terminal" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: custom-error-code-pages
  name: custom-error-code-pages
  namespace: openshift-config
data:
  error-page-404.http: |
    HTTP/1.0 404 File Not Found
    Cache-Control: no-cache
    Connection: close
    Content-Type: text/html

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="robots" content="nofollow,noarchive,noindex">
      <title>Not Found</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="404: Not Found">
      <meta name="description" content="The server can not find the requested page">
      <meta property="og:title" content="404: Not Found">
      <meta property="og:description" content="The server can not find the requested page">
      <meta property="twitter:title" content="404: Not Found">
      <meta property="twitter:description" content="The server can not find the requested page">
      <style>
        /** Idea author: https://codepen.io/robinselmer */
        html, body {
          margin: 0;
          padding: 0;
          min-height: 100%;
          height: 100%;
          width: 100%;
          font-family: monospace;
          font-size: 16px;
          overflow: hidden;
          word-break: keep-all;
        }
        body {
          box-sizing: border-box;
          background-color: #000;
          background-image: radial-gradient(#11581E, #041607);
          background-repeat: no-repeat;
          background-size: cover;
          color: rgba(128, 255, 128, 0.8);
          text-shadow: 0 0 11px rgba(51, 255, 51, 1), 0 0 2px rgba(255, 255, 255, 0.8);
        }
        .overlay {
          pointer-events: none;
          position: absolute;
          width: 100%;
          height: 100%;
          background: repeating-linear-gradient(
            180deg,
            rgba(0, 0, 0, 0) 0,
            rgba(0, 0, 0, 0.3) 50%,
            rgba(0, 0, 0, 0) 100%);
          background-size: auto 4px;
          z-index: 1;
        }
        .overlay::before {
          content: '';
          pointer-events: none;
          position: absolute;
          display: block;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          width: 100%;
          height: 100%;
          background-image: linear-gradient(
            0deg,
            transparent 0%,
            rgba(32, 128, 32, 0.2) 2%,
            rgba(32, 128, 32, 0.8) 3%,
            rgba(32, 128, 32, 0.2) 3%,
            transparent 100%);
          background-repeat: no-repeat;
          animation: scan 7.5s linear 0s infinite;
        }
        @keyframes scan {
          0% {
            background-position: 0 -100vh;
          }
          35%, 100% {
            background-position: 0 100vh;
          }
        }
        main {
          box-sizing: inherit;
          position: absolute;
          height: 100%;
          width: 1000px;
          max-width: 100%;
          padding: 64px;
          text-transform: uppercase;
        }
        h1 {
          font-size: 48px;
        }
        p {
          font-size: 24px;
        }
        .output {
          color: rgba(128, 255, 128, 0.8);
          text-shadow: 0 0 1px rgba(51, 255, 51, 0.4),
          0 0 2px rgba(255, 255, 255, 0.8);
        }
        .output::before {
          content: "> ";
        }
        a {
          color: #fff;
          text-decoration: none;
        }
        a::before {
          content: "[";
        }
        a::after {
          content: "]";
        }
        .error_code {
          color: white;
        }
      </style>
    </head>
    <body>
    <div class="overlay"></div>
    <main>
      <h1><span>Error</span> <span class="error_code">404</span></h1>
      <p class="output">The server can not find the requested page.</p>
      <p class="output"><span>Good luck</span>.</p>
    </main>
    </body>
    </html>

  error-page-503.http: |
    HTTP/1.0 503 Service Unavailable
    Cache-Control: no-cache
    Connection: close
    Content-Type: text/html

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="robots" content="nofollow,noarchive,noindex">
      <title>Service Unavailable</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="refresh" content="30">
      <meta name="title" content="503: Service Unavailable">
      <meta name="description" content="The server is temporarily overloading or down">
      <meta property="og:title" content="503: Service Unavailable">
      <meta property="og:description" content="The server is temporarily overloading or down">
      <meta property="twitter:title" content="503: Service Unavailable">
      <meta property="twitter:description" content="The server is temporarily overloading or down">
      <style>
        /** Idea author: https://codepen.io/robinselmer */
        html, body {
          margin: 0;
          padding: 0;
          min-height: 100%;
          height: 100%;
          width: 100%;
          font-family: monospace;
          font-size: 16px;
          overflow: hidden;
          word-break: keep-all;
        }
        body {
          box-sizing: border-box;
          background-color: #000;
          background-image: radial-gradient(#11581E, #041607);
          background-repeat: no-repeat;
          background-size: cover;
          color: rgba(128, 255, 128, 0.8);
          text-shadow: 0 0 11px rgba(51, 255, 51, 1), 0 0 2px rgba(255, 255, 255, 0.8);
        }
        .overlay {
          pointer-events: none;
          position: absolute;
          width: 100%;
          height: 100%;
          background: repeating-linear-gradient(
            180deg,
            rgba(0, 0, 0, 0) 0,
            rgba(0, 0, 0, 0.3) 50%,
            rgba(0, 0, 0, 0) 100%);
          background-size: auto 4px;
          z-index: 1;
        }
        .overlay::before {
          content: '';
          pointer-events: none;
          position: absolute;
          display: block;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          width: 100%;
          height: 100%;
          background-image: linear-gradient(
            0deg,
            transparent 0%,
            rgba(32, 128, 32, 0.2) 2%,
            rgba(32, 128, 32, 0.8) 3%,
            rgba(32, 128, 32, 0.2) 3%,
            transparent 100%);
          background-repeat: no-repeat;
          animation: scan 7.5s linear 0s infinite;
        }
        @keyframes scan {
          0% {
            background-position: 0 -100vh;
          }
          35%, 100% {
            background-position: 0 100vh;
          }
        }
        main {
          box-sizing: inherit;
          position: absolute;
          height: 100%;
          width: 1000px;
          max-width: 100%;
          padding: 64px;
          text-transform: uppercase;
        }
        h1 {
          font-size: 48px;
        }
        p {
          font-size: 24px;
        }
        .output {
          color: rgba(128, 255, 128, 0.8);
          text-shadow: 0 0 1px rgba(51, 255, 51, 0.4),
          0 0 2px rgba(255, 255, 255, 0.8);
        }
        .output::before {
          content: "> ";
        }
        a {
          color: #fff;
          text-decoration: none;
        }
        a::before {
          content: "[";
        }
        a::after {
          content: "]";
        }
        .error_code {
          color: white;
        }
      </style>
    </head>
    <body>
    <div class="overlay"></div>
    <main>
      <h1><span>Error</span> <span class="error_code">503</span></h1>
      <p class="output">The server is temporarily overloading or down.</p>
      <p class="output"><span>Good luck</span>.</p>
    </main>
    </body>
    </html>

{{- end }}
