---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert-tls
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: api-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-{{ .Values.certificates.letsencrypt.issuer }}
  commonName: "api.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}"
  dnsNames:
    - "api.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}"
