apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-democratic-csi
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: democratic-csi
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/democratic-csi
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: democratic-csi.driver.config.httpConnection.host
          value: {{ index .Values "democratic-csi" "driver" "config" "httpConnection" "host" }}
        - name: democratic-csi.driver.config.httpConnection.password
          value: {{ index .Values "democratic-csi" "driver" "config" "httpConnection" "password" }}
        - name: democratic-csi.driver.config.httpConnection.username
          value: {{ index .Values "democratic-csi" "driver" "config" "httpConnection" "username" }}
        - name: democratic-csi.driver.config.iscsi.targetPortal
          value: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetPortal" }}
