{{ if .Values.applications.readarr }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readarr
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: readarr
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/media-application
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}
          
        - name: storage.media.nfs.server
          value: {{ .Values.media.nfs.server }}
        - name: storage.media.nfs.path
          value: {{ .Values.media.nfs.path }}

        - name: application.name
          value: readarr
        - name: application.group
          value: Media
        - name: application.icon
          value: book-open
        - name: application.image
          value: 'https://raw.githubusercontent.com/Readarr/Readarr/develop/Logo/400.png'
        - name: application.description
          value: "Manages your eBook library"
        - name: app-template.service.main.ports.http.port
          value: '8787'

        # renovate custom-docker versioning=loose
        - name: app-template.controllers.main.containers.main.image.repository
          value: ghcr.io/k8s-at-home/readarr
        - name: app-template.controllers.main.containers.main.image.tag
          value: v0.1.1.1352
        - name: app-template.controllers.main.containers.main.image.pullPolicy
          value: IfNotPresent
        - name: app-template.controllers.main.containers.main.env.TZ
          value: America/New_York

        - name: app-template.serviceAccount.name
          value: readarr-sa
        - name: app-template.persistence.data.enabled
          value: "true"
        - name: app-template.persistence.data.existingClaim
          value: readarr-data-volume
        - name: app-template.persistence.config.enabled
          value: "true"
        - name: app-template.persistence.config.existingClaim
          value: readarr-config
        - name: app-template.persistence.config.globalMounts[0].path
          value: /config

        - name: app-template.defaultPodOptions.labels.app
          value: readarr
        - name: app-template.defaultPodOptions.labels.version
          value: v0.1.1.1352

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}