cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  group: ADSB
  iconColor: ''

pods:
  ultrafeeder:
    image:
      repository: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder
      # renovate: datasource=docker depName=ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder versioning=loose
      tag: latest-build-803
    env:
      LOGLEVEL: error
      HTTP_PORT: '8080'
      READSB_DEVICE_TYPE: rtlsdr
      READSB_RTLSDR_DEVICE: '1090'
      READSB_RTLSDR_PPM: '39'
      READSB_GAIN: 'autogain'
      READSB_RX_LOCATION_ACCURACY: '2'
      READSB_STATS_RANGE: 'true'
      ULTRAFEEDER_CONFIG: |
        adsb,adsb-dump978,30978,uat_in;
        mlathub,adsb-flightaware-mlat-beast-output,30105,beast_in;
        mlathub,adsb-planewatch,30105,beast_in;
        adsb,feed1.adsbexchange.com,30004,beast_reduce_plus_out;
        mlat,feed.adsbexchange.com,31090,39008;
        adsb,in.adsb.lol,30004,beast_reduce_plus_out;
        mlat,in.adsb.lol,31090,39001;
        adsb,feed.adsb.fi,30004,beast_reduce_plus_out;
        mlat,feed.adsb.fi,31090,39000;
      # mlathub,adsb-radarbox-mlat-beast-output,30105,beast_in;
      # adsb,feed.airplanes.live,30004,beast_reduce_plus_out;
      # adsb,feed.planespotters.net,30004,beast_reduce_plus_out;
      # adsb,feed.theairtraffic.com,30004,beast_reduce_plus_out;
      # adsb,data.avdelphi.com,24999,beast_reduce_plus_out;
      # adsb,skyfeed.hpradar.com,30004,beast_reduce_plus_out;
      # adsb,feed.radarplane.com,30001,beast_reduce_plus_out;
      # adsb,dati.flyitalyadsb.com,4905,beast_reduce_plus_out;
      # mlat,feed.airplanes.live,31090,39002;
      # mlat,mlat.planespotters.net,31090,39003;
      # mlat,feed.theairtraffic.com,31090,39004;
      # mlat,skyfeed.hpradar.com,31090,39005;
      # mlat,feed.radarplane.com,31090,39006;
      # mlat,dati.flyitalyadsb.com,30100,39007;
      # mlathub,radarvirtuel,30105,beast_in;
      READSB_FORWARD_MLAT_SBS: 'true'
      UPDATE_TAR1090: 'true'
      TAR1090_DEFAULTCENTERLAT: '35'
      TAR1090_DEFAULTCENTERLON: '70'
      TAR1090_MESSAGERATEINTITLE: 'true'
      TAR1090_PLANECOUNTINTITLE: 'true'
      TAR1090_ENABLE_AC_DB: 'true'
      TAR1090_FLIGHTAWARELINKS: 'true'
      TAR1090_SITESHOW: 'true'
      TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE: 'true'
      TAR1090_RANGE_OUTLINE_WIDTH: '2.0'
      TAR1090_RANGERINGSDISTANCES: '50,100,150,200'
      TAR1090_RANGERINGSCOLORS: "'#1A237E','#0D47A1','#42A5F5','#64B5F6'"
      TAR1090_USEROUTEAPI: 'true'
      GRAPHS1090_DARKMODE: 'true'

  dump978:
    image:
      repository: ghcr.io/ullbergm/docker-dump978
      # renovate: datasource=docker depName=ghcr.io/ullbergm/docker-dump978 versioning=loose
      tag: 2
    env:
      HTTP_PORT: '8080'
      READSB_DEVICE_TYPE: rtlsdr
      DUMP978_SDR_GAIN: 'autogain'
      DUMP978_SDR_PPM: '14'

  planewatch:
    image:
      repository: ghcr.io/plane-watch/docker-plane-watch
      # renovate: datasource=docker depName=ghcr.io/plane-watch/docker-plane-watch versioning=semver
      tag: v0.0.4
    env:
      BEASTHOST: 'adsb-ultrafeeder'

  flightaware:
    image:
      repository: ghcr.io/sdr-enthusiasts/docker-piaware
      # renovate: datasource=docker depName=ghcr.io/sdr-enthusiasts/docker-piaware versioning=semver
      tag: v9.0.1
    env:
      BEASTHOST: 'adsb-ultrafeeder'
      UAT_RECEIVER_TYPE: 'relay'
      UAT_RECEIVER_HOST: 'adsb-dump978'

  flightradar24:
    image:
      repository: ghcr.io/sdr-enthusiasts/docker-flightradar24
      # renovate: datasource=docker depName=ghcr.io/sdr-enthusiasts/docker-flightradar24 versioning=loose
      tag: 1.0.48-0
    env:
      BEASTHOST: 'adsb-ultrafeeder'

  adsbhub:
    image:
      repository: ghcr.io/sdr-enthusiasts/docker-adsbhub
      # renovate: datasource=docker depName=ghcr.io/sdr-enthusiasts/docker-adsbhub versioning=semver
      tag: 1.06
    env:
      SBSHOST: 'adsb-ultrafeeder'

  opensky:
    image:
      repository: ghcr.io/sdr-enthusiasts/docker-opensky-network
      # renovate: datasource=docker depName=ghcr.io/sdr-enthusiasts/docker-opensky-network versioning=loose
      tag: 2.1.7-1
    env:
      BEASTHOST: 'adsb-ultrafeeder'
