---
apiVersion: v2
description: A Helm chart to add my stuff.
name: ullberg-custom
version: 0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
